_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
                - 105
            "2":
                - 2
                - 3
                - 49
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.8
            "8":
                - 3
                - 2
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 10
hidden_size:
    value: 64
learning_rate:
    value: 0.0001
num_layers:
    value: 5
optimizer:
    value: rmsprop
weight_decay:
    value: 0.5
weight_init:
    value: Xavier
